### ISSUE TITLE
Not marking tasks as done

### ISSUE THREAD

**Issue by kerim** [flegfleg/logseq-reminders-sync#2] opened 2023-11-22 23:10 UTC
So things are working for me (as per my closed issue), but sync is only one way. Tasks marked done in Reminders are not getting marked done in Logseq.

**Comment by flegfleg** [comment] 2023-11-23 09:47
Do the tasks that are not marked "done" in Logseq…

*  still have a "processing" tag in Reminders? 
* is there an id in the notes field in Reminders? 
* can you click the link in Reminders, does it bring you back to the original task in Logseq?

**Comment by kerim** [comment] 2023-11-24 12:08
"Yes" to all three questions.

**Comment by flegfleg** [comment] 2023-11-26 22:55
OK, sorry you still have issues. I am super bisy right now, i'll try to look into it next weekend.

**Comment by kerim** [comment] 2023-11-26 23:49
Take your time. Thanks for helping.

**Comment by flegfleg** [comment] 2023-12-04 13:25
Hey @kerim, sorry it took me so long to get back to your issue. 
The only way i could reproduce your error was by disabling the API/setting a wrong token. 

Can you try the following: 
1. Double-check that the token is correct and the API is running (Symbol within Logseq should not be crossed through). 
2. Run the workflow directly from the Shortcuts app (not from a launcher since it may fail silently) and check if there are any errors.

**Comment by kerim** [comment] 2023-12-05 11:58
API is running, token is correct, and no errors.

Just to be clear on the issue:
Logseq > Reminders works fine. I just tested it and there is no "processing" tag during the first run. It also indicates that everything is working fine up to this point. 

However, after marking a task done in Reminders and running again Reminders > Logseq does not work (the Logseq task is not marked as DONE) and all the items get a "processing" tag during this second run - so somehow it isn't completing this process.

**Comment by Healer37** [comment] 2023-12-11 17:31
Encountering the same problem, requesting the author's assistance in resolving it.

**Comment by flegfleg** [comment] 2023-12-25 01:01
Hi, I have a feeling this is connected to Sonoma. 
are you both on macOS Sonoma?

**Comment by kerim** [comment] 2023-12-25 02:57
I am

**Comment by flegfleg** [comment] 2023-12-25 22:23
OK, i think i might have found the bug. Could not reproduce it on Ventura, but on Sonoma the shortcut failed as you described. 
Please try the updated shortcut (V 1.2) and let me know if it works: 
https://www.icloud.com/shortcuts/d69901f7a3a041c88ef668dff237536a

**Comment by kerim** [comment] 2023-12-25 23:27
Yes. This seems to do the trick. Thanks so much for that!

**Comment by flegfleg** [comment] 2023-12-26 08:25
You’re welcome!

**Closed as completed by flegfleg** 2023-12-26 08:25 UTC
